### ISSUE TITLE
`EdgeDB.Connection.handle_optimistic_execute_flow/5` did not handle message type `command_complete()`

### ISSUE THREAD

**Issue by Kabie** [nsidnev/edgedb-elixir#28]
When executing a simple query the second time, a `{:command_complete, %{capabilities: []}, "SELECT"}` is passed to `handle_optimistic_execute_flow`.

**Comment by nsidnev** [comment]
I'm sorry, I don't quite understand. Do you mean that this is a bug?  Do you get any errors when you try to run the query a second time?

`EdgeDB.Connection.handle_optimistic_execute_flow/5` handles only query preparation if necessary and error catching. Further processing of the server response is actually done by `EdgeDB.Connection.handle_execute_flow/4`, which should get a `CommandComplete` message from EdgeDB at the end.

I received the following messages for the `SELECT 1` query.
```elixir
iex(1)> {:ok, pid} = EdgeDB.start_link()
{:ok, #PID<0.248.0>}

iex(2)> EdgeDB.query(pid, "SELECT 1")
{:prepare_complete, %{capabilities: []}, :at_most_one,
 <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>,
 <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 5>>}
{:data, [data_element: <<0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 1>>]}
{:command_complete, %{capabilities: []}, "SELECT"}
{:ready_for_command, %{}, :not_in_transaction}
{:ok, %EdgeDB.Set{__items__: #MapSet<[1]>}}

iex(3)> EdgeDB.query(pid, "SELECT 1")
{:data, [data_element: <<0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 1>>]}
{:command_complete, %{capabilities: []}, "SELECT"}
{:ready_for_command, %{}, :not_in_transaction}
{:ok, %EdgeDB.Set{__items__: #MapSet<[1]>}}
```

**Comment by nsidnev** [comment]
So, I was able to reproduce this error when the prepared query does not return any data (e.g. an empty set). 
I've pushed a fix to master. If that doesn't help, could you please reopen this issue and share the statement causing new errors?

**Comment by Kabie** [comment]
Sorry for the origin post did not describe the query clearly. Yes, it returns an empty set, and it's working now.

Also great work for this lib!
